const sections=[
  ['dashboard','▦','Resumen'],['vehiculos','🚗','Vehículos'],['ventas','＄','Ventas'],['clientes','♙','Clientes'],
  ['contable','▤','Contable'],['operaciones','✓','Operaciones'],['bitacora','↺','Bitácora'],['vehgerencia','◆','Gerencia'],
  ['ctrlclientes','◎','Prospectos'],['mensajes','✉','Mensajes']
];
const titles={dashboard:'Resumen general',vehiculos:'Inventario de vehículos',ventas:'Registro de ventas',clientes:'Directorio de clientes',contable:'Contabilidad recuperada',operaciones:'Operaciones',bitacora:'Bitácora de actividad',vehgerencia:'Vehículos de gerencia',ctrlclientes:'Control de prospectos',mensajes:'Mensajes'};
let db={};let contable={};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('es-NI',{style:'currency',currency:'USD'}).format(Number(v)||0);
const date=v=>{if(!v)return '—';const d=new Date(v);return isNaN(d)?esc(v):d.toLocaleDateString('es-NI')};
const rows=n=>(db[n]||[]).map(x=>({...x.data,_rowId:x.id}));
document.querySelector('#nav').innerHTML=sections.map(([id,icon,label])=>`<a class="nav-item" data-section="${id}" href="#${id}"><span>${icon}</span>${label}</a>`).join('');
document.querySelector('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(b){location.hash=b.dataset.section;document.querySelector('.sidebar').classList.remove('open')}});
document.querySelector('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
document.querySelector('#download').onclick=()=>{const b=new Blob([JSON.stringify({capturado:new Date().toISOString(),tablas:db,contable_recuperado:contable},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='respaldo-nicauto-sis.json';a.click();URL.revokeObjectURL(a.href)};
function panel(title,subtitle,head,body){return `<div class="panel"><div class="panel-head"><div><h2>${title}</h2><p>${subtitle}</p></div><div class="toolbar"><input class="search" placeholder="Buscar en esta sección…" aria-label="Buscar"></div></div><div class="table-wrap"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div></div>`}
function searchable(){const input=document.querySelector('.search');if(!input)return;input.oninput=()=>{const q=input.value.toLowerCase();document.querySelectorAll('tbody tr').forEach(tr=>tr.hidden=!tr.innerText.toLowerCase().includes(q))}}
function dashboard(){const v=rows('vehiculos'),sales=rows('ventas'),clients=rows('clientes'),pros=rows('ctrlclientes');const total=sales.reduce((s,x)=>s+(Number(x.precio)||0),0);const acts=rows('bitacora').slice().sort((a,b)=>String(b.fecha).localeCompare(String(a.fecha))).slice(0,7);return `<div class="banner"><h2>Recuperación independiente lista</h2><p>Información preservada desde el sistema anterior. Esta copia no modifica la fuente original.</p></div><div class="cards"><div class="card metric"><span class="label">Vehículos</span><strong>${v.length}</strong><small>registros recuperados</small><div class="bar"></div></div><div class="card metric"><span class="label">Ventas</span><strong>${sales.length}</strong><small>${money(total)} registrados</small><div class="bar"></div></div><div class="card metric"><span class="label">Clientes</span><strong>${clients.length}</strong><small>en el directorio</small><div class="bar"></div></div><div class="card metric"><span class="label">Prospectos</span><strong>${pros.length}</strong><small>en seguimiento</small><div class="bar"></div></div></div><div class="grid2">${panel('Inventario reciente','Vehículos preservados',['Vehículo','Placa','Año','Estado'],v.slice(0,8).map(x=>`<tr><td><b>${esc(x.marca)} ${esc(x.modelo)}</b></td><td>${esc(x.placa||'—')}</td><td>${esc(x.anio||'—')}</td><td><span class="badge green">${esc(x.estado||'Disponible')}</span></td></tr>`).join(''))}<div class="panel"><div class="panel-head"><div><h2>Actividad reciente</h2><p>Últimos movimientos recuperados</p></div></div><ul class="activity">${acts.map(x=>`<li><b>${esc(x.tipo||'Actividad')}</b><small>${esc(x.desc||'Sin descripción')} · ${date(x.fecha)}</small></li>`).join('')||'<li>Sin actividad recuperada</li>'}</ul></div></div>`}
function generic(name){const r=rows(name);const configs={vehiculos:[['Vehículo','Placa','Año','Color','Estado','Precio'],x=>[`<b>${esc(x.marca)} ${esc(x.modelo)}</b>`,esc(x.placa||'—'),esc(x.anio||'—'),esc(x.color||'—'),`<span class="badge green">${esc(x.estado||'—')}</span>`,`<span class="money">${money(x.precio)}</span>`]],ventas:[['Fecha','Comprador','Vehículo','Estado','Precio','Ganancia'],x=>[date(x.fecha),esc(x.nombreFactura||x.compradorId||'—'),esc(x.vehiculoId||'—'),`<span class="badge">${esc(x.estado||'—')}</span>`,`<span class="money">${money(x.precio)}</span>`,`<span class="money">${money(x.ganancia)}</span>`]],clientes:[['Nombre','Cédula','Teléfono','Correo','Rol'],x=>[`<b>${esc(x.nombre)}</b>`,esc(x.cedula||'—'),esc(x.tel||'—'),esc(x.email||'—'),`<span class="badge">${esc(x.rol||'Cliente')}</span>`]],bitacora:[['Fecha','Tipo','Descripción','Vehículo'],x=>[date(x.fecha),`<span class="badge gold">${esc(x.tipo||'—')}</span>`,esc(x.desc||'—'),esc(x.vehId||'—')]],vehgerencia:[['Vehículo','Placa','Año','Responsable','Uso','Gasto mensual'],x=>[`<b>${esc(x.marca)} ${esc(x.modelo)}</b>`,esc(x.placa||'—'),esc(x.anio||'—'),esc(x.resp||'—'),esc(x.uso||'—'),`<span class="money">${money(x.gastomes)}</span>`]],ctrlclientes:[['Fecha','Nombre','Teléfono','Interés','Vendedor','Estado'],x=>[date(x.fecha),`<b>${esc(x.nombre)}</b>`,esc(x.cel||'—'),esc(x.interes||'—'),esc(x.vendNombre||'—'),`<span class="badge">${esc(x.estado||'—')}</span>`]],mensajes:[['Fecha','Canal','Nombre','Mensaje'],x=>[date(x.ts),`<span class="badge">${esc(x.canal||'—')}</span>`,esc(x.nombre||'—'),esc(x.texto||'—')]]};const [headers,map]=configs[name];return panel(titles[name],`${r.length} registros recuperados`,headers,r.map(x=>`<tr>${map(x).map(v=>`<td>${v}</td>`).join('')}</tr>`).join(''))}
function accounting(){const cuentas=contable.cuentas||[],rend=contable.rendicionHistorial||[],movs=rend.flatMap(x=>x.movs||[]);const saldo=cuentas.reduce((s,x)=>s+(Number(x.saldo)||0),0);return `<div class="cards"><div class="card metric"><span class="label">Cuentas</span><strong>${cuentas.length}</strong><small>${money(saldo)} en saldos</small><div class="bar"></div></div><div class="card metric"><span class="label">Rendiciones</span><strong>${rend.length}</strong><small>historial recuperado</small><div class="bar"></div></div><div class="card metric"><span class="label">Movimientos</span><strong>${movs.length}</strong><small>preservados</small><div class="bar"></div></div></div>${panel('Cuentas recuperadas','Cuentas por cobrar y pagar preservadas',['Fecha','Tipo','Persona / descripción','Monto','Saldo','Estado'],cuentas.map(x=>`<tr><td>${date(x.fecha)}</td><td><span class="badge">${esc(x.tipo||'—')}</span></td><td>${esc(x.persona||x.desc||'—')}</td><td class="money">${money(x.monto)}</td><td class="money">${money(x.saldo)}</td><td><span class="badge gold">${esc(x.estado||'—')}</span></td></tr>`).join(''))}<div class="note">Se recuperaron ${cuentas.length} cuentas, ${rend.length} rendiciones y ${movs.length} movimientos. El resto del registro contable había sido sobrescrito en la fuente.</div>`}
function operations(){const rend=contable.rendicionHistorial||[],movs=rend.flatMap(h=>(h.movs||[]).map(m=>({...m,rendicion:h.numero})));const total=movs.reduce((s,x)=>s+(Number(x.monto)||0),0);return `<div class="cards"><div class="card metric"><span class="label">Rendiciones</span><strong>${rend.length}</strong><small>cierres recuperados</small><div class="bar"></div></div><div class="card metric"><span class="label">Movimientos</span><strong>${movs.length}</strong><small>gastos de operaciones</small><div class="bar"></div></div><div class="card metric"><span class="label">Total rendido</span><strong>C$ ${new Intl.NumberFormat('es-NI').format(total)}</strong><small>según el respaldo</small><div class="bar"></div></div></div>${panel('Rendición de cuentas — Operaciones','Movimientos recuperados hasta el 17/07/2026',['Rendición','Fecha','Clasificación','Descripción','Monto'],movs.map(x=>`<tr><td>#${esc(x.rendicion)}</td><td>${date(x.fecha)}</td><td><span class="badge gold">${esc(x.clasif||x.categoria||'Operaciones')}</span></td><td>${esc(x.desc||x.descripcion||'—')}</td><td class="money">C$ ${new Intl.NumberFormat('es-NI').format(Number(x.monto)||0)}</td></tr>`).join(''))}<div class="note">Las tareas y la lista de personal no estaban en los respaldos, pero sí se recuperaron las 8 rendiciones con sus 82 movimientos de Operaciones.</div>`}
function render(){const id=location.hash.slice(1)||'dashboard';document.querySelector('#title').textContent=titles[id]||titles.dashboard;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.section===id));const app=document.querySelector('#app');app.innerHTML=id==='dashboard'?dashboard():id==='contable'?accounting():id==='operaciones'?operations():generic(id);searchable()}
async function init(){try{const [a,b]=await Promise.all([fetch('data/respaldo_actual_completo.json'),fetch('data/contable_recuperado_hasta_18-07-2026.json')]);const all=await a.json();db=all.tablas||{};contable=await b.json();render()}catch(e){document.querySelector('#app').innerHTML='<div class="panel empty"><h2>No se pudieron cargar los datos</h2><p>Actualiza la página para intentarlo nuevamente.</p></div>'}}
window.addEventListener('hashchange',render);init();
